name: Deploy

on:
  push:
    tags:
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Grant Execute Permission for gradlew
        run: chmod +x gradlew

      - name: Read gradle.properties
        uses: BrycensRanch/read-properties-action@v1
        id: properties
        with:
          file: gradle.properties
          property: mod_version

      - name: Compare Versioning
        run: |
          if [${{ steps.properties.outputs.mod_version != github.ref_name }}]
          then
            exit 1
          fi

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Publish to maven
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish -Pcleanroom_maven=${{ vars.CLEANROOM_MAVEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: build/libs/
